### ISSUE TITLE
從我的最愛新增訂閱 列表不完整

### ISSUE THREAD

**Issue by schaoss** [Yukaii/vscode-ptt#11]
**你遇到了什麼問題？**

我的最愛列表中，只會顯示第一頁 ( 前 20 筆 ) 的內容。

**如何重現**

1. 登入
2. 點選 從我的最愛新增訂閱

**使用環境**

- vscode-ptt 版本: 0.2.0
- VSCode 版本: 1.33.1
- 作業系統: Windows 10

**Comment by kevinptt0323** [comment]
[ptt-client@0.6.1](https://github.com/kevinptt0323/ptt-client/releases/tag/v0.6.1) 已修正。

**Comment by Yukaii** [comment]
在 #15 一併升級了，感謝 @kevinptt0323 上游支援 😍
