### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by sunneo** [Yukaii/vscode-ptt#16]
**你遇到了什麼問題？**
not work

請詳細的描述一下
打開extension後狀態一直在loading，按下refresh按鈕，得到錯誤"ptt.refresh-article not found"
文章沒有顯示出來

**如何重現**
0. 環境: Ubuntu 18.04 64bit xfce  (xubuntu 18.04)
1. NoMachine to remote host
2. Open VsCode
3. install extension
4. open extension 'vscode-ptt'
5. done.

**使用環境**
Xubuntu 18.04
vscode installed from snap
install vscode-ptt from https://marketplace.visualstudio.com/items?itemName=Yukai.vscode-ptt&ssr=false#qna

- vscode-ptt 版本: 0.3.1
- VSCode 版本: 1.36.2
- 作業系統:  Linux

**Comment by brianchul** [comment]
相同問題 無法登入
點選更多功能僅顯示這個
<img width="394" alt="螢幕快照 2019-10-28 下午1 51 45" src="https://user-images.githubusercontent.com/18157275/67654944-1a168f80-f98a-11e9-9d69-3eede2062d3c.png">

macOS 10.14.6
Vscode 版本: 1.39.2
vscode-ptt 版本: 0.3.1

**Comment by JosephT5566** [comment]
稍微試了一下，似乎是ptt-client中的login，在最近的更新之後無法連線@@

**Comment by Yukaii** [comment]
可能是最近站方開始限制 websocket 的 origin 了 😅 剛好這兩天關了一個 PR （隨便猜猜）

- https://github.com/ptt/pttbbs/pull/24
- https://github.com/ptt/pttbbs/commit/de63cdf1cff06b317a1e3597423c1dd8a3279fc6

要試試把 origin 換成 `^app://` 有沒有舊 🤣 

https://github.com/ptt/pttbbs/commit/de63cdf1cff06b317a1e3597423c1dd8a3279fc6#diff-aed484195b5021a9cbbe97cff74bbeddR31

**Comment by Yukaii** [comment]
是很想上 upstream 標籤啦，不過這應該是 upstream 的 upstream 的問題，說起來這不就是 origin 嗎（冷

**Comment by Yukaii** [comment]
發現 ptt-client 預設的 origin 就是 www.ptt.cc 了，看來問題不是在這呢 😂 

https://github.com/kevinptt0323/ptt-client/blob/master/src/sites/ptt/config.ts

記得 keven 和我提過其實不用再搭一個 [proxy](https://github.com/Yukaii/vscode-ptt/blob/master/src/proxy.ts)，要試試看移掉會如何

**Comment by JosephT5566** [comment]
試著不傳入proxy來new ptt實體，看來是會直接採用預設的origin來建立，應該是沒問題
不過在login那邊還是不行呢~ 或許真的是websocket QQ

**Comment by mikeqoo1** [comment]
我也有相同問題

![image](https://user-images.githubusercontent.com/30303712/67752966-ec574680-fa6e-11e9-95d4-e52196940c6c.png)

CentOS Linux release 7.7.1908 (Core)
vscode 版本: 1.39.2
vscode-ptt 版本: 0.3.1

**Comment by kevinptt0323** [comment]
> 可能是最近站方開始限制 websocket 的 origin 了 sweat_smile 剛好這兩天關了一個 PR （隨便猜猜）
> 
>     * [ptt/pttbbs#24](https://github.com/ptt/pttbbs/pull/24)
> 
>     * [ptt/pttbbs@de63cdf](https://github.com/ptt/pttbbs/commit/de63cdf1cff06b317a1e3597423c1dd8a3279fc6)
> 
> 
> 要試試把 origin 換成 `^app://` 看有沒有救 rofl
> 
> [ptt/pttbbs@de63cdf#diff-aed484195b5021a9cbbe97cff74bbeddR31](https://github.com/ptt/pttbbs/commit/de63cdf1cff06b317a1e3597423c1dd8a3279fc6#diff-aed484195b5021a9cbbe97cff74bbeddR31)

我試了一下是可以的，怕未來被卡的話，就用 `app://pcman` 吧XD

**Comment by Yukaii** [comment]
@kevinptt0323 太帥啦！！

**Comment by Yukaii** [comment]
v0.3.2 版本已發佈！

https://marketplace.visualstudio.com/items?itemName=Yukai.vscode-ptt
