### ISSUE TITLE
MVP tasks

### ISSUE THREAD

**Issue by Yukaii** [Yukaii/vscode-ptt#2]
- [x] 使用者登入
- [x] 登入資訊儲存
	- [x] 看有什麼系統級 credential 的做法，或是用 Memento。抄 VSCode GitHub
- [x] 登出，清除登入資訊
- [x] VSCode Tree API 研究
- [x] 選取我的最愛看板
- [x] 文章列表
	- ~~載入更多，ptt-client 預設載入二十筆~~ 再說
- [x] 閱讀文章
	- [x] VSCode content provider API?
	- [x] 在主編輯器顯示，簡單的 parse 文章內容和推文，輸出純文字如何？
- [x] Refresh 最新文章
- [x] ~~Iconography~~ 先用 VSC 範例給的，剛好也是列表意味
- [x] Update README & Docs
- [x] Publish to store
- [x] Load more articles
- ~~好歹要一個 Logo~~ 好了啦
- ~~Share on VSCodeTaiwan~~ 完成度高一點再 PO

**Comment by kevinptt0323** [comment]
https://github.com/kevinptt0323/ptt-client/blob/master/src/sites/ptt/bot.js#L144
可以用 `getArticles(boardname, offset)`，即可得到 id 為 `[offset-19, offset]` 的文章列表。

**Comment by Yukaii** [comment]
@kevinptt0323 耶 ❤️

**Comment by Yukaii** [comment]
先關票。

MVP 算是告一段落，但距離 1.0.0 還有段距離 w，慢慢邁進
