### ISSUE TITLE
保留已登入使用者

### ISSUE THREAD

**Issue by Yukaii** [Yukaii/vscode-ptt#6]
狠狠的加上 upstream tag

**Comment by kevinptt0323** [comment]
[ptt-client@0.5.1](https://github.com/kevinptt0323/ptt-client/releases/tag/v0.5.1)
```javascript
async function login(username: string, password: string, kick: boolean=true): Promise<void> {
}
```

**Comment by Yukaii** [comment]
@kevinptt0323 💯

**Comment by Yukaii** [comment]
@kevinptt0323 發現 0.5.1 的 bot.js 沒有更新 kick 參數，可能在發佈之前建制失敗？

![Screen Shot 2019-04-02 at 8 41 51 PM](https://user-images.githubusercontent.com/4230968/55403161-cbd21700-5587-11e9-87b1-801d99ef018c.png)

**Comment by kevinptt0323** [comment]
再 publish 到 0.5.2 一次
我的失誤==
太久沒 publish

非常感謝
